# Generated by Django 5.1.7 on 2025-03-26 00:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('category', models.CharField(max_length=30, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('places', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Places')),
                ('has_transport', models.BooleanField(default=False, verbose_name='Has Transport?')),
                ('has_meal', models.BooleanField(default=False, verbose_name='Has Meal?')),
                ('has_guide', models.BooleanField(default=False, verbose_name='Has Guide?')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plans.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('picture_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('picture', models.ImageField(default=None, upload_to='galery/')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plans.plan', verbose_name='Plans')),
            ],
        ),
        migrations.CreateModel(
            name='Plan_date',
            fields=[
                ('plan_date_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('plan_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plans.plan', verbose_name='Plan')),
            ],
        ),
    ]
