# Generated by Django 5.1.7 on 2025-03-26 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('total_cost', models.IntegerField(verbose_name='Total Cost')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Sale date')),
                ('plan_date_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plans.plan_date', verbose_name='Plan')),
            ],
        ),
    ]
