# Generated by Django 5.1.7 on 2025-03-22 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('total_cost', models.IntegerField(verbose_name='Total Cost')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plans.plans', verbose_name='Plan')),
            ],
        ),
    ]
