# Generated by Django 5.1.6 on 2025-03-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='number_of_people',
            field=models.IntegerField(default=1, verbose_name='Number of People'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(default='Tarjeta', max_length=50, verbose_name='Payment Method'),
        ),
    ]
