# Generated by Django 5.1.7 on 2025-03-22 16:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('content', models.CharField(max_length=1000, verbose_name='Review Content')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rate')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plans.plans', verbose_name='Plan')),
            ],
        ),
    ]
